import "bootstrap/dist/css/bootstrap.min.css";
import AddBootstrap from "./AddBootstrap";
import NavBar from "./NavBar";
import Footer from "./Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <AddBootstrap />
        {children}
        <Footer />
      </body>
    </html>
  );
}
